# This file contains configurations for both PostgreSQL and MySQL, uncomment
# the one you wish to use and keep the other commented out.

# -------------------------------- PostgreSQL ----------------------------------
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db
  # The following username and password are used for both development and test
  # environments.

development:
  <<: *default
  port: 5432
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  port: 5432
  database: <%= ENV['POSTGRES_DB'] %>

  # HEROKU
  # Heroku uses the DATABASE_URL environment variable to configure the DB
  # connection. You should *NOT* set adapter, database, username, password, host
  # or port in this file.

  # AMAZON ELASTIC BEANSTALK + AMAZON RDS
  # These environment variables are available in any Beanstalk environment
  # that is linked to an RDS instance.
  # database: <%= ENV['RDS_DB_NAME'] %>
  # username: <%= ENV['RDS_USERNAME'] %>
  # password: <%= ENV['RDS_PASSWORD'] %>
  # host: <%= ENV['RDS_HOSTNAME'] %>
  # port: <%= ENV['RDS_PORT'] %>

# ---------------------------------  MySQL -------------------------------------
#default: &default
#  adapter: mysql2
#  encoding: utf8
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  # The following username and password are used for both development and test
#  # environments.
#  username: root
#  password: localdbpass
#  socket: /var/run/mysqld/mysqld.sock
#
#development:
#  <<: *default
#  database: needp_development
#
#test:
#  <<: *default
#  database: needp_test
#
production:
  <<: *default
  encoding: utf8
  database: d9v32q0599kl5l
  username: yoiizqcixsxxva
  password: a25970811cd3e861375b7b949c2292796347cadfb6601f7b8c31511fe240a0eb
  host: ec2-174-129-234-111.compute-1.amazonaws.com
  port: 5432